# Generated by Django 5.2.4 on 2025-07-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0002_pegawai_username_alter_pegawai_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='pegawai',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='pegawai',
            name='username',
        ),
        migrations.AlterField(
            model_name='pegawai',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
