# Generated by Django 5.2.4 on 2025-07-23 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0003_alter_pegawai_managers_remove_pegawai_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pegawai',
            name='atasan_langsung',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bawahan_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pegawai',
            name='gelar_belakang',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pegawai',
            name='gelar_depan',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pegawai',
            name='jenis_kelamin',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pegawai',
            name='pangkat_gol_ruang',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pegawai',
            name='tanggal_lahir',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pegawai',
            name='tempat_lahir',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pegawai',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='alamat email'),
        ),
        migrations.CreateModel(
            name='Bidang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_bidang', models.CharField(max_length=150, unique=True)),
                ('kepala_bidang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kepala_dari_bidang', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UnitKerja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_unit', models.CharField(max_length=150, unique=True)),
                ('bidang', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unit_kerja_list', to='pegawai.bidang')),
                ('kepala_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kepala_dari_unit', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pegawai',
            name='unit_kerja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anggota_list', to='pegawai.unitkerja'),
        ),
    ]
