# Generated by Django 5.2.4 on 2025-07-24 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0004_pegawai_atasan_langsung_pegawai_gelar_belakang_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pegawai',
            name='role',
            field=models.CharField(choices=[('PEGAWAI', 'Pegawai'), ('ATASAN', 'Atasan'), ('ADMIN', 'Admin')], default='PEGAWAI', max_length=10),
        ),
    ]
