# Generated by Django 5.2.4 on 2025-07-24 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0005_pegawai_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jabatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_jabatan', models.CharField(max_length=150, unique=True)),
                ('deskripsi', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='pegawai',
            name='jabatan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pegawai_list', to='pegawai.jabatan'),
        ),
    ]
