# Generated by Django 5.2.4 on 2025-08-05 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0006_jabatan_pegawai_jabatan'),
    ]

    operations = [
        migrations.AddField(
            model_name='pegawai',
            name='alamat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pegawai',
            name='jenis_pegawai',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pegawai',
            name='nik',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='pegawai',
            name='pendidikan_terakhir',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pegawai',
            name='penempatan_awal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pegawai',
            name='status_kepegawaian',
            field=models.CharField(blank=True, default='Aktif', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pegawai',
            name='status_perkawinan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
