# Generated by Django 5.2.4 on 2025-07-23 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RencanaHasilKerja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deskripsi', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='IndikatorKinerja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deskripsi', models.TextField()),
                ('target', models.CharField(max_length=255)),
                ('rhk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indikator_list', to='spekta.rencanahasilkerja')),
            ],
        ),
        migrations.CreateModel(
            name='SKP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode_awal', models.DateField()),
                ('periode_akhir', models.DateField()),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Diajukan', 'Diajukan'), ('Persetujuan', 'Persetujuan'), ('Ditolak', 'Ditolak')], default='Draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skp_list', to=settings.AUTH_USER_MODEL)),
                ('pejabat_penilai', models.ForeignKey(help_text='Atasan langsung pegawai', on_delete=django.db.models.deletion.PROTECT, related_name='skp_dinilai', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='rencanahasilkerja',
            name='skp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rhk_list', to='spekta.skp'),
        ),
    ]
