# Generated by Django 5.2.4 on 2025-07-23 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spekta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterPerilakuKerja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_perilaku', models.CharField(max_length=255, unique=True)),
                ('uraian_perilaku', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PerilakuKerja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ekspektasi_khusus', models.TextField(blank=True, help_text='Diisi oleh pimpinan saat persetujuan.', null=True)),
                ('master_perilaku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spekta.masterperilakukerja')),
                ('skp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perilaku_kerja_list', to='spekta.skp')),
            ],
            options={
                'unique_together': {('skp', 'master_perilaku')},
            },
        ),
    ]
