# Generated by Django 5.2.4 on 2025-07-23 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spekta', '0002_masterperilakukerja_perilakukerja'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluasiAksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realisasi', models.TextField(blank=True, help_text='Diisi oleh Pegawai', null=True)),
                ('feedback_atasan', models.TextField(blank=True, help_text='Diisi oleh Atasan', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BuktiDukung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_bukti', models.URLField(max_length=512)),
                ('deskripsi', models.CharField(blank=True, max_length=255, null=True)),
                ('evaluasi_aksi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bukti_dukung_list', to='spekta.evaluasiaksi')),
            ],
        ),
        migrations.CreateModel(
            name='PeriodePenilaian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_periode', models.CharField(help_text='Contoh: Januari, Triwulan I', max_length=100)),
                ('tanggal_awal', models.DateField()),
                ('tanggal_akhir', models.DateField()),
                ('rating_hasil_kerja', models.CharField(blank=True, help_text='Contoh: Sesuai Ekspektasi', max_length=50, null=True)),
                ('rating_perilaku_kerja', models.CharField(blank=True, max_length=50, null=True)),
                ('predikat_kinerja', models.CharField(blank=True, help_text='Contoh: Baik', max_length=50, null=True)),
                ('skp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periode_penilaian_list', to='spekta.skp')),
            ],
        ),
        migrations.AddField(
            model_name='evaluasiaksi',
            name='periode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluasi_aksi_list', to='spekta.periodepenilaian'),
        ),
        migrations.CreateModel(
            name='RencanaAksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deskripsi', models.TextField()),
                ('rhk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aksi_list', to='spekta.rencanahasilkerja')),
            ],
        ),
        migrations.AddField(
            model_name='evaluasiaksi',
            name='rencana_aksi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluasi_list', to='spekta.rencanaaksi'),
        ),
        migrations.CreateModel(
            name='EvaluasiPerilaku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_atasan', models.TextField(blank=True, help_text='Diisi oleh Atasan', null=True)),
                ('perilaku_kerja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluasi_list', to='spekta.perilakukerja')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluasi_perilaku_list', to='spekta.periodepenilaian')),
            ],
            options={
                'unique_together': {('periode', 'perilaku_kerja')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='evaluasiaksi',
            unique_together={('periode', 'rencana_aksi')},
        ),
    ]
