# Generated by Django 5.2.4 on 2025-07-24 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spekta', '0003_evaluasiaksi_buktidukung_periodepenilaian_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skp',
            name='pendekatan',
            field=models.CharField(default='Kuantitatif', max_length=50),
        ),
    ]
