# Generated by Django 5.2.4 on 2025-07-24 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spekta', '0004_skp_pendekatan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lampiran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dukungan_sumber_daya', models.TextField(blank=True, null=True)),
                ('skema_pertanggungjawaban', models.TextField(blank=True, null=True)),
                ('konsekuensi', models.TextField(blank=True, null=True)),
                ('skp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lampiran', to='spekta.skp')),
            ],
        ),
    ]
