# Generated by Django 5.2.4 on 2025-07-25 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spekta', '0005_lampiran'),
    ]

    operations = [
        migrations.AddField(
            model_name='rencanahasilkerja',
            name='aspek',
            field=models.CharField(default='Kuantitas', max_length=50),
        ),
        migrations.AddField(
            model_name='rencanahasilkerja',
            name='intervensi_atasan_text',
            field=models.TextField(blank=True, help_text='RHK pimpinan yang diintervensi', null=True),
        ),
    ]
