# Generated by Django 5.2.4 on 2025-07-25 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spekta', '0006_rencanahasilkerja_aspek_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='periodepenilaian',
            name='penilai_saat_itu',
            field=models.ForeignKey(blank=True, help_text='Snapshot penilai pada saat periode ini dievaluasi', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periode_dinilai_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
