# Generated by Django 5.2.4 on 2025-07-25 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spekta', '0007_periodepenilaian_penilai_saat_itu'),
    ]

    operations = [
        migrations.AddField(
            model_name='rencanahasilkerja',
            name='jenis_rhk',
            field=models.CharField(choices=[('Utama', 'Utama'), ('Tambahan', 'Tambahan')], default='Utama', max_length=10),
        ),
    ]
