# Generated by Django 5.2.4 on 2025-07-26 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0006_jabatan_pegawai_jabatan'),
        ('spekta', '0008_rencanahasilkerja_jenis_rhk'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodepenilaian',
            name='jabatan_saat_itu',
            field=models.ForeignKey(blank=True, help_text='Snapshot jabatan pegawai pada periode ini', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pegawai.jabatan'),
        ),
        migrations.AddField(
            model_name='periodepenilaian',
            name='unit_kerja_saat_itu',
            field=models.ForeignKey(blank=True, help_text='Snapshot unit kerja pegawai pada periode ini', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pegawai.unitkerja'),
        ),
    ]
