# Generated by Django 5.2.4 on 2025-07-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spekta', '0009_periodepenilaian_jabatan_saat_itu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rencanaaksi',
            name='target',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
