# Generated by Django 5.2.4 on 2025-07-28 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spekta', '0010_rencanaaksi_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluasiaksi',
            name='dasar_realisasi',
            field=models.TextField(blank=True, help_text='Dasar dari realisasi', null=True),
        ),
    ]
