# Generated by Django 5.2.4 on 2025-07-28 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spekta', '0011_evaluasiaksi_dasar_realisasi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buktidukung',
            name='link_bukti',
            field=models.CharField(max_length=512),
        ),
    ]
