# Generated by Django 5.2.4 on 2025-07-28 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spekta', '0012_alter_buktidukung_link_bukti'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodepenilaian',
            name='capaian_organisasi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
