# Generated by Django 5.2.4 on 2025-07-30 03:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spekta', '0013_periodepenilaian_capaian_organisasi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='skp',
            name='atasan_pejabat_penilai',
            field=models.ForeignKey(blank=True, help_text='Atasan dari pejabat penilai', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='skp_diawasi', to=settings.AUTH_USER_MODEL),
        ),
    ]
