# Generated by Django 5.2.4 on 2025-07-30 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spekta', '0014_skp_atasan_pejabat_penilai'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodepenilaian',
            name='catatan_rekomendasi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
