# Generated by Django 5.2.4 on 2025-07-31 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spekta', '0015_periodepenilaian_catatan_rekomendasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='rencanaaksi',
            name='periode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rencana_aksi_list', to='spekta.periodepenilaian'),
        ),
    ]
