# Generated by Django 5.2.4 on 2025-07-31 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spekta', '0016_rencanaaksi_periode'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodepenilaian',
            name='force_unlocked',
            field=models.BooleanField(default=False, help_text='Buka kunci penilaian manual oleh Superadmin'),
        ),
    ]
