# Generated by Django 5.2.4 on 2025-08-02 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spekta', '0017_periodepenilaian_force_unlocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='skp',
            name='catatan_penolakan',
            field=models.TextField(blank=True, help_text='Diisi oleh atasan saat SKP ditolak.', null=True),
        ),
    ]
